create table abstract_device (
  id int8 generated by default as identity,
  device_type varchar(255),
  primary key (id)
);
create table abstract_incoming (
  id int8 generated by default as identity,
  incoming_type varchar(255),
  client_id int8,
  incoming_source_id int8,
  primary key (id)
);
create table clients (
  id int8 generated by default as identity,
  email varchar(255),
  phone_number varchar(255),
  telegram_nickname varchar(255),
  name varchar(255) not null,
  primary key (id)
);
create table departments (
  id int8 generated by default as identity,
  primary key (id)
);
create table email_devices (
  host varchar(255),
  password varchar(255),
  port int8,
  protocol varchar(255),
  username varchar(255),
  id int8 not null,
  primary key (id)
);
create table email_messages (
  content oid,
  incoming_email varchar(255),
  id int8 not null,
  primary key (id)
);
create table incoming_source (
  source_type varchar(31) not null,
  id int8 generated by default as identity,
  device_id int8 not null,
  primary key (id)
);
create table lead_states (
  state_name varchar(255) not null,
  order_number int4 not null,
  primary key (state_name)
);
create table leads (
  id int8 generated by default as identity,
  lead_to_client int8 not null,
  lead_to_state varchar(255) not null,
  lead_to_user varchar(255) not null,
  primary key (id)
);
create table refresh_jwt (
  token varchar(255) not null,
  login varchar(255),
  primary key (token)
);
create table report_templates (
  id int8 generated by default as identity,
  template_data TEXT not null,
  primary key (id)
);
create table reports (
  id int8 generated by default as identity,
  report_data bytea not null,
  report_to_template int8 not null,
  primary key (id)
);
create table roles (
  type_of_role varchar(31) not null,
  role_type_id varchar(255) not null,
  primary key (role_type_id)
);
create table users_role (
  user_id varchar(255) not null,
  role_id varchar(255) not null,
  primary key (user_id, role_id)
);
create table usrs (
  login varchar(255) not null,
  name varchar(255) not null,
  password varchar(255) not null,
  subordinate_ids int8,
  head_ids int8,
  primary key (login)
);
alter table
  if exists abstract_incoming
add
  constraint FKpcdcyfji9tw43h2x41oqsxfoj foreign key (client_id) references clients;
alter table
  if exists abstract_incoming
add
  constraint FKqd8fktost9bpti0797gsnlbq9 foreign key (incoming_source_id) references incoming_source;
alter table
  if exists email_devices
add
  constraint FKbukv0lwrkpcgwigulitsd95d7 foreign key (id) references abstract_device;
alter table
  if exists email_messages
add
  constraint FK7gent6n5k0w1pwd1jbchyp8oy foreign key (id) references abstract_incoming;
alter table
  if exists incoming_source
add
  constraint FK7d2axn551tjjewcrey8s01ers foreign key (device_id) references abstract_device;
alter table
  if exists leads
add
  constraint FK3n9yskjo0gfkj4a49rarom0uk foreign key (lead_to_client) references clients;
alter table
  if exists leads
add
  constraint FK2nbwrii3ajdwkeci8tindbqcg foreign key (lead_to_state) references lead_states;
alter table
  if exists leads
add
  constraint FKb254wxmrtflxffko08w9q0jf foreign key (lead_to_user) references usrs;
alter table
  if exists reports
add
  constraint FK8cxiqowejcl10hnopcw83m9q4 foreign key (report_to_template) references report_templates;
alter table
  if exists users_role
add
  constraint FKeejqlb4gq1av9540jg66ju2pi foreign key (role_id) references roles;
alter table
  if exists users_role
add
  constraint FKiwpniw4rvmbbs3w81keahhvx foreign key (user_id) references usrs;
alter table
  if exists usrs
add
  constraint FKlimb2vpudp733vvkq4cpgn2ld foreign key (subordinate_ids) references departments;
alter table
  if exists usrs
add
  constraint FKb5lcnyrnnywb2rrvtvrfxufrp foreign key (head_ids) references departments;
