CREATE TABLE abstract_device
             (
                          id int8 generated BY DEFAULT AS identity,
                          device_type VARCHAR(255),
                          PRIMARY KEY (id)
             );
CREATE TABLE abstract_incoming
             (
                          id int8 generated BY DEFAULT AS identity,
                          incoming_type VARCHAR(255),
                          client_id int8,
                          incoming_source_id int8,
                          PRIMARY KEY (id)
             );
CREATE TABLE clients
             (
                          id int8 generated BY DEFAULT AS identity,
                          email             VARCHAR(255),
                          phone_number      VARCHAR(255),
                          telegram_nickname VARCHAR(255),
                          name              VARCHAR(255) NOT NULL,
                          PRIMARY KEY (id)
             );
CREATE TABLE departments
             (
                          id int8 generated BY DEFAULT AS identity,
                          PRIMARY KEY (id)
             );
CREATE TABLE email_devices
             (
                          host     VARCHAR(255),
                          password VARCHAR(255),
                          port int8,
                          protocol VARCHAR(255),
                          username VARCHAR(255),
                          id int8 NOT NULL,
                          PRIMARY KEY (id)
             );
CREATE TABLE email_messages
             (
                          content oid,
                          incoming_email VARCHAR(255),
                          id int8 NOT NULL,
                          PRIMARY KEY (id)
             );
CREATE TABLE incoming_source
             (
                          source_type VARCHAR(31) NOT NULL,
                          id int8 generated BY DEFAULT AS identity,
                          device_id int8 NOT NULL,
                          PRIMARY KEY (id)
             );
CREATE TABLE lead_states
             (
                          state_name VARCHAR(255) NOT NULL,
                          order_number int4 NOT NULL,
                          PRIMARY KEY (state_name)
             );
CREATE TABLE leads
             (
                          id int8 generated BY DEFAULT AS identity,
                          lead_to_client int8 NOT NULL,
                          lead_to_state VARCHAR(255) NOT NULL,
                          lead_to_user int8 NOT NULL,
                          PRIMARY KEY (id)
             );
CREATE TABLE report_templates
             (
                          id int8 generated BY DEFAULT AS identity,
                          template_data text NOT NULL,
                          PRIMARY KEY (id)
             );
CREATE TABLE reports
             (
                          id int8 generated BY DEFAULT AS identity,
                          report_data bytea NOT NULL,
                          report_to_template int8 NOT NULL,
                          PRIMARY KEY (id)
             );
CREATE TABLE ROLES
             (
                          type_of_role VARCHAR(31) NOT NULL,
                          role_type_id VARCHAR(255) NOT NULL,
                          PRIMARY KEY (role_type_id)
             );
CREATE TABLE users_role
             (
                          user_id int8 NOT NULL,
                          role_id VARCHAR(255) NOT NULL,
                          PRIMARY KEY (user_id, role_id)
             );
CREATE TABLE usrs
             (
                          id int8 generated BY DEFAULT AS identity,
                          login    VARCHAR(255) NOT NULL,
                          name     VARCHAR(255) NOT NULL,
                          password VARCHAR(255) NOT NULL,
                          subordinate_ids int8,
                          head_ids int8,
                          PRIMARY KEY (id)
             );
ALTER TABLE IF EXISTS abstract_incoming ADD CONSTRAINT fkpcdcyfji9tw43h2x41oqsxfoj FOREIGN KEY (client_id) REFERENCES clients;
ALTER TABLE IF EXISTS abstract_incoming ADD CONSTRAINT fkqd8fktost9bpti0797gsnlbq9 FOREIGN KEY (incoming_source_id) REFERENCES incoming_source;
ALTER TABLE IF EXISTS email_devices ADD CONSTRAINT fkbukv0lwrkpcgwigulitsd95d7 FOREIGN KEY (id) REFERENCES abstract_device;
ALTER TABLE IF EXISTS email_messages ADD CONSTRAINT fk7gent6n5k0w1pwd1jbchyp8oy FOREIGN KEY (id) REFERENCES abstract_incoming;
ALTER TABLE IF EXISTS incoming_source ADD CONSTRAINT fk7d2axn551tjjewcrey8s01ers FOREIGN KEY (device_id) REFERENCES abstract_device;
ALTER TABLE IF EXISTS leads ADD CONSTRAINT fk3n9yskjo0gfkj4a49rarom0uk FOREIGN KEY (lead_to_client) REFERENCES clients;
ALTER TABLE IF EXISTS leads ADD CONSTRAINT fk2nbwrii3ajdwkeci8tindbqcg FOREIGN KEY (lead_to_state) REFERENCES lead_states;
ALTER TABLE IF EXISTS leads ADD CONSTRAINT fkb254wxmrtflxffko08w9q0jf FOREIGN KEY (lead_to_user) REFERENCES usrs;
ALTER TABLE IF EXISTS reports ADD CONSTRAINT fk8cxiqowejcl10hnopcw83m9q4 FOREIGN KEY (report_to_template) REFERENCES report_templates;
ALTER TABLE IF EXISTS users_role ADD CONSTRAINT fkeejqlb4gq1av9540jg66ju2pi FOREIGN KEY (role_id) REFERENCES ROLES;
ALTER TABLE IF EXISTS users_role ADD CONSTRAINT fkiwpniw4rvmbbs3w81keahhvx FOREIGN KEY (user_id) REFERENCES usrs;
ALTER TABLE IF EXISTS usrs ADD CONSTRAINT fklimb2vpudp733vvkq4cpgn2ld FOREIGN KEY (subordinate_ids) REFERENCES departments;
ALTER TABLE IF EXISTS usrs ADD CONSTRAINT fkb5lcnyrnnywb2rrvtvrfxufrp FOREIGN KEY (head_ids) REFERENCES departments;